### ISSUE TITLE
可以将 MBProgressHUD 依赖库升级到 1.2.0 吗？

### ISSUE THREAD

**Issue by szmichaelyb** [Dengni8023/JGSourceBase#1]
### 可以将 MBProgressHUD 依赖库升级到 1.2.0 吗？

![image](https://user-images.githubusercontent.com/9857312/163118739-8fd0cc64-916d-4a02-a6bb-dc3440de114b.png)

**Comment by Dengni8023** [comment]
内部未限制MBProgressHUD版本
