### ISSUE TITLE
v1.4.0 被移除掉了？

### ISSUE THREAD

**Issue by szmichaelyb** [Dengni8023/JGSourceBase#2]
#### v1.4.0 被移除掉了吗？怎么更新，反而回退到 v1.3.2了。

![image](https://user-images.githubusercontent.com/9857312/182088487-0db62e4c-bd30-4b3a-a535-3f0adfa0c094.png)

cocopods.org 的版本还是 v1.3.1

![image](https://user-images.githubusercontent.com/9857312/182088787-331de5d8-6fcf-4825-b440-cc2bcaa35516.png)

**Comment by Dengni8023** [comment]
已发布的最新版本是1.3.1；1.4.0是开发过程版本，无新内容变化，开发版本修改为1.3.2了
