### ISSUE TITLE
[SecurityKeyboard]子库针对苹果系统自带输入法搜索表情导致崩溃

### ISSUE THREAD

**Issue by szmichaelyb** [Dengni8023/JGSourceBase#3]
#### [SecurityKeyboard]子库针对苹果系统自带输入法搜索表情导致崩溃

![image](https://github.com/user-attachments/assets/a827ad25-c5b2-4710-bbd4-bfbe3abd8911)

**Comment by Dengni8023** [comment]
问题已修复，请验证

commit id：e17ef73525cd1940c7a99cd625a96dd02ceb1911
